site_name: "{paycorp.io}"
nav:
    - Home: 'index.md'
    - 'Support':
        - 'Main': 'support/index.md'
        - 'Error': 'support/Error.md'
        - 'Shown More': 'support/showmore.md'
    - Installation:
        - 'Cloud': 'installation/index.md'
        - 'Bank': 'installation/bankinstallation.md'
    - API: './API/'
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.tabbed
theme:
  name: material
  logo: assets/logo.png
  favicon: images/favicon.png
  features:
    - navigation.tabs
    - navigation.sections
    - content.code.annotate
  palette:
    primary: deep purple
extra:
  analytics:
    provider: google
    property: G-XXXXXXXXXX
  consent:
    title: Cookie consent
    description:
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
